{
  imports = [
    ./filebrowser.nix
    ./frigate.nix
    ./glances.nix
    ./homepage.nix
    ./immich.nix
    ./it-tools.nix
    ./jellyfin.nix
    ./librespeed.nix
    ./linkwarden.nix
    ./microbin.nix
    ./nextcloud.nix
    ./onlyoffice.nix
    ./paperless.nix
    ./pgadmin.nix
    ./portainer.nix
    ./qbittorrent.nix
    ./samba.nix
    ./shinobi.nix
    ./speedtest-tracker.nix
    ./tubearchivist.nix
    ./uptime-kuma.nix
    ./vaultwarden.nix
  ];
}
